[package]
name = "transitguard-reader-simulator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
transitguard-device-protocol = { path = "../../crates/device-protocol" }
transitguard-domain = { path = "../../crates/domain" }
transitguard-fare-engine = { path = "../../crates/fare-engine" }

[lints]
workspace = true
