[package]
name = "transitguard-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
transitguard-device-protocol = {
    path = "../device-protocol"
}

[lints]
workspace = true
